AWSTemplateFormatVersion: '2010-09-09'
Description: 'work

  Rest API to manage Ticket of travel

  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateTripsRecordFunction:
    Description: CreateTripsRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripsRecordFunction
      - Arn
  GetTripsRecordsByCoutryFunction:
    Description: GetTripsRecordsByCoutry Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsRecordsByCoutryFunction
      - Arn
  
  GetTripsRecordsByCityFunction:
    Description: GetTripsRecordsByCity Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsRecordsByCityFunction
      - Arn

Resources:
  CreateTripsRecordFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        CreateTripsRecord:
          Properties:
            Method: post
            Path: /trips
          Type: Api
      Handler: br.com.iwe.handler.CreateTripsRecord::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  
  GetTripsRecordsByCoutryFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripsRecordsByCoutry:
          Properties:
            Method: get
            Path: /trips/{country}/findByCoutry
            RequestParameters:
            - method.request.querystring.Coutry
          Type: Api
      Handler: br.com.iwe.handler.GetTripsRecordsByCoutry::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function


  GetTripsRecordsByCityFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripsRecordsByCity:
          Properties:
            Method: get
            Path: /trips/{country}/findByCity
            RequestParameters:
            - method.request.querystring.City
          Type: Api
      Handler: br.com.iwe.handler.GetTripsRecordsByCity::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function

  


