AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    trip

    Rest API to manage trips

Globals:
    Function:
        Timeout: 20
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref Trip
            ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripsRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.CreateTripsRecord::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref Trip     
     Events:
       CreateTripsRecord:
         Type: Api
         Properties:
           Path: /trips
           Method: post
           
              
  GetTripsRecordsByCoutryFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetTripsRecordsByCoutry::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref Trip
     Events:
       GetTripsRecordsByCoutry:
         Type: Api
         Properties:
           Path: /trips/{country}/findByCoutry
           Method: get
           RequestParameters:
              - method.request.querystring.Coutry

  GetTripsRecordsByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/trip-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetTripsRecordsByCity::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref Trip
     Events:
       GetTripsRecordsByCity:
         Type: Api
         Properties:
           Path: /trips/{country}/findByCity
           Method: get
           RequestParameters:
              - method.request.querystring.Coutry
              
  Trip:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: country
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: reason
          AttributeType: S            
    
      BillingMode: PAY_PER_REQUEST              

Outputs:

    CreateTripsRecordFunction:
      Description: "CreateStudyRecord Lambda Function ARN"
      Value: !GetAtt CreateTripsRecordFunction.Arn
      
    GetTripsRecordsByCoutryFunction:
      Description: "GetStudyRecordsByPeriod Lambda Function ARN"
      Value: !GetAtt GetTripsRecordsByCoutryFunction.Arn
      
    GetTripsRecordsByCityFunction:
      Description: "GetStudyRecordsByTag Lambda Function ARN"
      Value: !GetAtt GetTripsRecordsByCityFunction.Arn
      
   
     
